### PR TITLE
Removed support for KerbMinder

### PR DESCRIPTION
**Pull request by ftiff**
Hey @macmule ! 

KerbMinder doesn't check anymore for ADPassMon's plist following a discussion with @pmbuko 
As I'm don't use ADPassMon or bind to AD, could you please verify I've not broken anything?

### CODE REVIEW

**Comment by macmule** [comment]
I don't use KerbMinder.. so not sure how to test. :(

**Comment by ftiff** [comment]
if you use Kerberos, make sure it can still refresh tickets (kinit/klist…). It shouldn't depend at all on KerbMinder, no need for you to install it.

**Comment by macmule** [comment]
Reopening as looks related to https://github.com/macmule/ADPassMon/issues/83

**Comment by macmule** [comment]
See https://github.com/macmule/ADPassMon/issues/84

With the conflicts, i cannot merge the PR.. but will add the changes to a future build.

**Pull request closed without merging**
